### PR TITLE
Fixes wrong mkdir default mode

### LINKED ISSUE #25: Wrong default mode for mkdir?
Hi,
the `Amp\File\mkdir` function defines `0644` as default mode (https://github.com/amphp/file/blob/master/lib/functions.php#L245).
But PHP's `\mkdir` function defines the same default mode as `0777` (http://php.net/manual/en/function.mkdir.php).

Is there any reason why the default mode of `Amp\File` is different from the PHP one?

### PR DESCRIPTION
**Pull request by mmenozzi**
Fixes #25

### CODE REVIEW

**Comment by bwoebi** [comment]
Thanks :-)

**Comment by mmenozzi** [comment]
You're welcome! Are you going to tag a new version with this fix?

**Comment by kelunik** [comment]
@mmenozzi Of course, want it now? :smile:

**Comment by mmenozzi** [comment]
Take your time no problem! 😄

**Comment by kelunik** [comment]
@mmenozzi Just noticed that the interface has the same default. Do you want to provide another PR for that?

https://github.com/amphp/file/blob/59d14c779eb479998ec887593fcef14db074fd50/lib/Driver.php#L154

**Comment by mmenozzi** [comment]
Damn you're right. I'm on it.

**Pull request merged**
